import './styles/sass/main.scss';
import './ts/interfaces.ts';
import './ts/burger-menu.ts';
import './ts/slider.ts';
import './ts/video-section.ts';
import './ts/custom-video-player.ts';
import './ts/explore-slider.ts';
import './ts/gallery.ts';
import './ts/tickets.ts';